### ISSUE TITLE
Recipe not created when inventory is closed

### ISSUE THREAD

**Issue by dhgameryt** [MLG-Fortress/CustomItemRegistry#3]
When you created a new recipe, of a registered item, it is not saved, nor in the recipes.yml file of the plugin, it remains blank, no matter how hard you try.

I already tried deleting the plugin and removed the other plugins, but even so it always happens, I'm in 1.13 and this error makes it impossible to create any crafting, and I do not know how to create a recipe from recipes.yml in the plugin folder .

**Comment by RoboMWM** [comment]
Please provide steps/screenshots of steps performed to create a recipe.

**Comment by RoboMWM** [comment]
Also, if there is an error, please paste it.

**Comment by dhgameryt** [comment]
1: first, I get a diamond sword, then using /citem name, I give it a name and then I add a lore
![image](https://user-images.githubusercontent.com/44879137/48960970-e2b88b00-ef4f-11e8-944e-13d870154cea.png)
2: I register the object with /citem register and then I get it with /citem get sword1
![image](https://user-images.githubusercontent.com/44879137/48961055-7c803800-ef50-11e8-8b67-687b12e0ffa7.png)
3: use /crecipe shaped sword1 and I open the menu to create the recipe
![image](https://user-images.githubusercontent.com/44879137/48961092-bea97980-ef50-11e8-8254-557202208f3d.png)
4: I create a recipe and press the E key to close the menu, then I try to make the item and not
![image](https://user-images.githubusercontent.com/44879137/48961113-e4368300-ef50-11e8-851e-2cfefd57b518.png)
![image](https://user-images.githubusercontent.com/44879137/48961122-f0224500-ef50-11e8-8128-c3d136e15361.png)
5: I look in the plugin folder and the document is blank
![image](https://user-images.githubusercontent.com/44879137/48961139-0fb96d80-ef51-11e8-8435-1fc94a38c128.png)

**Comment by dhgameryt** [comment]
try a lot of things but I do not know what the error is, in the console of the server there is no type of error or warning

**Comment by dhgameryt** [comment]
When I press the E key when I finish the recipe, I do not receive any message, I do not know if this is normal

**Comment by RoboMWM** [comment]
Ok yea you're supposed to get a message when you close the inventory. Thanks for the steps and screenshots! Will try to check things on my end.

**Comment by dhgameryt** [comment]
Muchas gracias por contestar, espero que se pueda solucionar este problema, repito, ya tenga este plugin en este servidor, bueno, estare esperando cualquier cosa

**Comment by dhgameryt** [comment]
Thank you very much for answering, I hope that this problem can be solved, I repeat, I already have only this plugin on the server, well, I'll be waiting for anything.

**Comment by RoboMWM** [comment]
Weird, I was able to register a recipe with no issues at all. What's the output of `/version` and `/version CustomItemRecipes`?

**Comment by RoboMWM** [comment]
Also tested on a fresh server, no issues either.

**Comment by dhgameryt** [comment]
Ok, now I do.

**Comment by dhgameryt** [comment]
this is the server version
![image](https://user-images.githubusercontent.com/44879137/48971159-f4a03980-eff4-11e8-9508-78a8528ce238.png)
this is the version of the plugin
![image](https://user-images.githubusercontent.com/44879137/48971252-f3bbd780-eff5-11e8-9d2d-9dc839588277.png)

**Comment by dhgameryt** [comment]
this is how it appears when I load the plugin
![image](https://user-images.githubusercontent.com/44879137/48971323-b9066f00-eff6-11e8-8804-e1089b03a5ae.png)
Try spigot and bukkit but it does not work, all in 1.13

**Comment by RoboMWM** [comment]
Can you try 1.13.2? It's definitely working on 1.13.2 for me. Only other thing I could think of is if you're not using a vanilla client...?

**Comment by RoboMWM** [comment]
Try without optifine or whatever, idk if it could be the that it's not sending an InventoryClose packet...

**Comment by RoboMWM** [comment]
![](https://i.imgur.com/18HFDys.png)

![](https://i.imgur.com/zS9VdfR.png)

I made sure the recipes.yml and items.yml were blank. I didn't use optifine though so idk if that may be why.

**Comment by RoboMWM** [comment]
Also, vanilla seems to add that "Combat" thing in the name between lore and display name.
![](https://i.imgur.com/VPvezzQ.png)

**Comment by dhgameryt** [comment]
I'm going to try it on with minecraft 1.13 vanilla and then with 1.13.2 vanilla

**Comment by dhgameryt** [comment]
I do not get Combat in 1.13

**Comment by dhgameryt** [comment]
and it does not work in 1.13 vanilla

**Comment by dhgameryt** [comment]
Could you pass me the recipes.yml document with 1 or more recipes created so I can copy it and create my recipes?

**Comment by dhgameryt** [comment]
Here is a video that I made to show you how it works
https://www.youtube.com/watch?v=w555xfe02Pk

**Comment by RoboMWM** [comment]
Just saw the video - perhaps you can try updating spigot? Maybe see if it works on Paper? https://papermc.io/downloads (just download and run paperclip.jar instead of spigot.jar)

It seems there were some updates regarding recipes but nothing that I can directly see in the commits so idk if updating spigot will do anything. But see if paper works.

Also, the "Combat" part is showing for me even with the advanced debug info. Are you sure you're using the vanilla client?

**Comment by dhgameryt** [comment]
yes, I use the latest version and I've tried it many times already

**Comment by dhgameryt** [comment]
maybe I should just try another plugin

**Comment by RoboMWM** [comment]
It's just not making any sense. Can you try using event debug to see what events occur when you open the chest? I'd like to find out if the event actually fires. https://www.spigotmc.org/resources/eventdebug.5940/

If not I can make a debug version of this plugin but I just see no reason why it wouldn't fire.

**Comment by dhgameryt** [comment]
![image](https://user-images.githubusercontent.com/44879137/49388869-b9dc8680-f703-11e8-8f79-8956a0ca93d5.png)
![image](https://user-images.githubusercontent.com/44879137/49388937-df699000-f703-11e8-8878-b00d335b950e.png)
![image](https://user-images.githubusercontent.com/44879137/49388967-f27c6000-f703-11e8-9d7d-f21f2eb122d7.png)
![image](https://user-images.githubusercontent.com/44879137/49388983-01631280-f704-11e8-9e41-5e0d1444ae39.png)

**Comment by dhgameryt** [comment]
Could you enter my server and try it yourself?

**Comment by RoboMWM** [comment]
Sure, what's the IP? You can join my IRC channel and tell me if you don't want to publicly post it here. https://kiwiirc.com/client/irc.spi.gt/#robomwm

**Comment by dhgameryt** [comment]
Thank you, really thank you for all the help you have given me, I thank you and I hope you have a good life: D, finally I can give this post closed, I hope we can be good friends!

**Comment by RoboMWM** [comment]
Seems that spigot silently removed custom inventory holder support for most inventories, but Paper added it back in a recent 1.13.2 build https://github.com/PaperMC/Paper/blob/684bd2adbcbfbfdc14cfca5cdf5aa39cadbb4a7c/Spigot-Server-Patches/0403-Restore-custom-InventoryHolder-support.patch

If spigot doesn't do anything about this I likely will have to add in spigot compatibility myself via removing the inventoryholder check...

**Comment by dhgameryt** [comment]
Nostalgic
